import type { ISPPlan } from "@/types/portal";

export const DEFAULT_ISP_PLANS: ISPPlan[] = [
  {
    id: "plan-fiber-30",
    name: "Spectra Starter 30 Mbps",
    download_speed_mbps: 30,
    upload_speed_mbps: 30,
    price_inr: 399,
    data_limit_gb: null,
    billing_cycle: "monthly",
    description: "Symmetric 30 Mbps Fiber with Unlimited Data for basic browsing & streaming.",
    tag: "Budget",
  },
  {
    id: "plan-fiber-50",
    name: "Spectra Essential 50 Mbps",
    download_speed_mbps: 50,
    upload_speed_mbps: 50,
    price_inr: 499,
    data_limit_gb: null,
    billing_cycle: "monthly",
    description: "Ideal for small households, HD video streaming, and work-from-home.",
    tag: "Popular",
  },
  {
    id: "plan-fiber-100",
    name: "Spectra Pro 100 Mbps",
    download_speed_mbps: 100,
    upload_speed_mbps: 100,
    price_inr: 699,
    data_limit_gb: null,
    billing_cycle: "monthly",
    description: "High-speed 100 Mbps symmetric fiber with ultra-low gaming latency.",
    is_popular: true,
    tag: "Best Value",
  },
  {
    id: "plan-fiber-200",
    name: "Spectra Turbo 200 Mbps",
    download_speed_mbps: 200,
    upload_speed_mbps: 200,
    price_inr: 899,
    data_limit_gb: null,
    billing_cycle: "monthly",
    description: "200 Mbps symmetric bandwidth for 4K streaming and multi-device households.",
  },
  {
    id: "plan-fiber-300",
    name: "Spectra GigaFiber 300 Mbps",
    download_speed_mbps: 300,
    upload_speed_mbps: 300,
    price_inr: 999,
    data_limit_gb: null,
    billing_cycle: "monthly",
    description: "Flagship 300 Mbps Gigabit fiber with zero throttling and 24x7 SLA guarantee.",
    is_popular: true,
    tag: "Gigabit Grade",
  },
  {
    id: "plan-fiber-500",
    name: "Spectra Ultra 500 Mbps",
    download_speed_mbps: 500,
    upload_speed_mbps: 500,
    price_inr: 1499,
    data_limit_gb: null,
    billing_cycle: "monthly",
    description: "Ultra-fast 500 Mbps fiber for creator studios, heavy downloads, and home labs.",
  },
  {
    id: "plan-fiber-1000",
    name: "Spectra Enterprise 1 Gbps",
    download_speed_mbps: 1000,
    upload_speed_mbps: 1000,
    price_inr: 2499,
    data_limit_gb: null,
    billing_cycle: "monthly",
    description: "Enterprise-grade 1000 Mbps true symmetric dedicated line with static IP support.",
    tag: "Enterprise",
  },
];
